SRC=src/ui
INDEX_FILE=$SRC/index.ts
rm -f $INDEX_FILE

echo "// this file file was generated by scripts/generateIndex.sh" >> $INDEX_FILE
for path in $SRC/*; do
  file=$(basename "$path")
  ext="${file##*.}"
  name="${file%.*}"
  if [[ "$name" != "index" ]]; then
    if [[ -d "$path" || "$ext" == "ts" || "$ext" == "tsx" || "$ext" == "js" || "$ext" == "jsx" ]]; then
      if [[ "${name:0:1}" == [[:lower:]] ]]; then
        echo "export * as $name from './$name';" >> $INDEX_FILE
      fi
    fi
  fi
done

for path in $SRC/*; do
  file=$(basename "$path")
  ext="${file##*.}"
  name="${file%.*}"
  if [[ "$name" != "index" ]]; then
    if [[ -d "$path" || "$ext" == "ts" || "$ext" == "tsx" || "$ext" == "js" || "$ext" == "jsx" ]]; then
      if [[ "${name:0:1}" != [[:lower:]] ]]; then
        echo "export { default as $name } from './$name';" >> $INDEX_FILE
      fi
    fi
  fi
done

